In [1]:
import numpy as np

In [22]:
a = np.zeros((20,20))
print(a)
print(a.shape)
H, W = a.shape
tile_size_y, tile_size_x = 10, 10

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [23]:
for i in range(0, H, tile_size_y):
    for j in range(0, W, tile_size_x):
        if i + tile_size_y <= H and j + tile_size_x <= W:
            a[i:i+tile_size_y, j:j+tile_size_x] = 1
            print('=========',i,j,'=========')
            print(a)

========= 0 0 =========
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [27]:
limit = (1117 // 256) * 256
print(limit)

1024


In [28]:
import re
granule = 'a/b/c/1.tif'
re.search(r'\d{1,2}', granule.split('/')[-1]).group()

def get_z(granule):
    return re.search(r'\d{1,2}', granule.split('/')[-1]).group()

'1'

In [29]:
def sample_tiles(args, queue=None):
    """
    args:
        arr: tif, 7 bands, RGB time t-1, RGB time t, loss time t
    """
    img_arr = args['arr'][6]
    H, W = img_arr.shape
    tile_size_x = args['tile_size_x']
    tile_size_y = args['tile_size_y']
    limit_y, limit_x = (H // tile_size_y) * tile_size_y, (W // tile_size_x) * tile_size_x
    for i in range(0, limit_y, tile_size_y):
        for j in range(0, limit_x, tile_size_x):
            tile = np.copy(args['img_arr'][i:i+tile_size_y, j:j+tile_size_x])
            if check_quality_label(tile):
                save_tile(j, i, tile_size_x, tile_size_y, args)

def save_tile(x, y, tile_size_x, tile_size_y, args):
    year = args['year']
    z = get_z(args['input_filename'])
    out_path = args['out_path']
    output_filename = args['output_filename']
    img_arr0 = np.copy(args['img_arr'][:3, y:y+tile_size_y, x:x+tile_size_x])
    img_arr1 = np.copy(args['img_arr'][3:6, y:y+tile_size_y, x:x+tile_size_x])
    loss = np.copy(args['img_arr'][6, y:y+tile_size_y, x:x+tile_size_x])
    out_file0 = os.path.join(out_input_path, output_filename.format(year=year-1, z=z, x=x, y=y))
    out_file1 = os.path.join(out_input_path, output_filename.format(year=year, z=z, x=x, y=y))
    out_file_loss = os.path.join(out_label_path, output_labelname.format(year=year, z=z, x=x, y=y))
    
    np.save(out_file0, img_arr0)
    np.save(out_file1, img_arr1)
    np.save(out_file_loss, loss)
